networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.3:20201210_gotip_arm64
        gid: '1002'
        uid: '1001'
        username: moksleivis
      context: /home/moksleivis/Desktop/AirportApp-1/.ddev/db-build
      dockerfile: /home/moksleivis/Desktop/AirportApp-1/.ddev/.dbimageBuild/Dockerfile
    command: ''
    container_name: ddev-Vejas-db
    environment:
      COLUMNS: '194'
      DDEV_HOSTNAME: vejas.ddev.site
      DDEV_PHP_VERSION: '7.4'
      DDEV_PRIMARY_URL: http://vejas.ddev.site
      DDEV_PROJECT: Vejas
      DDEV_PROJECT_TYPE: laravel
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: Vejas
      DDEV_TLD: ddev.site
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      IS_DDEV_PROJECT: "true"
      LINES: '20'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m
      timeout: 2m
    hostname: Vejas-db
    image: drud/ddev-dbserver-mariadb-10.3:20201210_gotip_arm64-Vejas-built
    labels:
      com.ddev.app-type: laravel
      com.ddev.approot: /home/moksleivis/Desktop/AirportApp-1
      com.ddev.platform: ddev
      com.ddev.site-name: Vejas
    ports:
    - 127.0.0.1::3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: 1001:1002
    volumes:
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - source: /home/moksleivis/Desktop/AirportApp-1/.ddev
      target: /mnt/ddev_config
      type: bind
    - ddev-global-cache:/mnt/ddev-global-cache:rw
  dba:
    container_name: ddev-Vejas-dba
    environment:
      HTTPS_EXPOSE: 8037:8036
      HTTP_EXPOSE: 8036:8036
      PMA_PASSWORD: root
      PMA_USER: root
      TZ: ''
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: vejas.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: Vejas-dba
    image: phpmyadmin:5
    labels:
      com.ddev.app-type: laravel
      com.ddev.approot: /home/moksleivis/Desktop/AirportApp-1
      com.ddev.platform: ddev
      com.ddev.site-name: Vejas
    links:
    - db:db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:20201229_php7.4
        gid: '1002'
        uid: '1001'
        username: moksleivis
      context: /home/moksleivis/Desktop/AirportApp-1/.ddev/web-build
      dockerfile: /home/moksleivis/Desktop/AirportApp-1/.ddev/.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-Vejas-web
    environment:
      COLUMNS: '194'
      DDEV_DOCROOT: public
      DDEV_HOSTNAME: vejas.ddev.site
      DDEV_PHP_VERSION: '7.4'
      DDEV_PRIMARY_URL: http://vejas.ddev.site
      DDEV_PROJECT: Vejas
      DDEV_PROJECT_TYPE: laravel
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: Vejas
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: public
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: http://vejas.ddev.site
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTPS_EXPOSE: 443:80,8026:8025
      HTTP_EXPOSE: 80:80,8025:8025
      IS_DDEV_PROJECT: "true"
      LINES: '20'
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: vejas.ddev.site
    external_links:
    - ddev-router:vejas.ddev.site
    extra_hosts:
    - host.docker.internal:172.17.0.1
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m
      timeout: 2m
    hostname: Vejas-web
    image: drud/ddev-webserver:20201229_php7.4-Vejas-built
    labels:
      com.ddev.app-type: laravel
      com.ddev.approot: /home/moksleivis/Desktop/AirportApp-1
      com.ddev.platform: ddev
      com.ddev.site-name: Vejas
    links:
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: 1001:1002
    volumes:
    - consistency: cached
      source: /home/moksleivis/Desktop/AirportApp-1
      target: /var/www/html
      type: bind
    - /home/moksleivis/Desktop/AirportApp-1/.ddev:/mnt/ddev_config:ro
    - /home/moksleivis/Desktop/AirportApp-1/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - /home/moksleivis/Desktop/AirportApp-1/.ddev/apache:/etc/apache2/sites-enabled:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: Vejas-mariadb

